### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by themojilla** [ethanselzer/react-lazy-tree#1]
Hi and tanx for this great repo 
It seems that this repo version is not sync with react 16 ?

can u fix it?

**Comment by ethanselzer** [comment]
Hi @mojilla - Thanks for opening this issue! Please see the [release notes for v1.0.4](https://github.com/ethanselzer/react-lazy-tree/releases/tag/v1.0.4).

**Comment by themojilla** [comment]
thank you so much :)
